# Generated by Django 2.2.24 on 2021-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210617_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
    ]
